//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChMoPay
    {
        public int Id { get; set; }
        public Nullable<int> ChMoPay_ChargeMonthly_Id { get; set; }
        public Nullable<int> ChMoPay_Account_Id { get; set; }
        public Nullable<long> ChMoPayDueAmount { get; set; }
        public string ChMoPayDueDate { get; set; }
        public Nullable<short> ChMoPayDelayMonth { get; set; }
    }
}
