//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGuarantor
    {
        public int id { get; set; }
        public Nullable<int> Guarantor_Loan_Id { get; set; }
        public Nullable<int> Guarantor_Info_Id { get; set; }
        public Nullable<byte> Guarantor_GuaranteeType_Id { get; set; }
        public Nullable<byte> Guarantor_BlockType_Id { get; set; }
        public string GuarantorReceiptNumber { get; set; }
        public Nullable<long> GuarantorAmount { get; set; }
        public Nullable<long> GuarantorBlockAmount { get; set; }
        public Nullable<bool> GuarantorBlock { get; set; }
        public string GuarantorDescription { get; set; }
    }
}
