//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntroducer
    {
        public int Id { get; set; }
        public Nullable<int> Introducer_Loan_Id { get; set; }
        public Nullable<byte> Introducer_IntroducerType_Id { get; set; }
        public Nullable<int> Introducer_Info_Id { get; set; }
        public Nullable<short> Introducer_Institution_Id { get; set; }
        public string IntroducerDescription { get; set; }
    }
}
