//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstallment
    {
        public int Id { get; set; }
        public Nullable<int> Installment_Loan_Id { get; set; }
        public Nullable<byte> Installment_PaymentType_Id { get; set; }
        public Nullable<long> InstallmentDueAmount { get; set; }
        public Nullable<long> InstallmentAmount { get; set; }
        public string InstallmentReceiptNumber { get; set; }
        public Nullable<long> InstallmentTotalPaid { get; set; }
        public Nullable<long> InstallmentRemaining { get; set; }
        public string InstallmentPaymentDate { get; set; }
        public string InstallmentDueDate { get; set; }
        public Nullable<short> InstallmentDelayDay { get; set; }
        public string InstallmentDescription { get; set; }
    }
}
