//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoan
    {
        public int Id { get; set; }
        public Nullable<int> Loan_Personnel_Id { get; set; }
        public Nullable<byte> Loan_LoanType_Id { get; set; }
        public Nullable<long> LoanAmount { get; set; }
        public string LoanDate { get; set; }
        public Nullable<byte> LoanInstallmentNum { get; set; }
        public string LoanInstallmentFirstPayDate { get; set; }
        public Nullable<byte> LoanInstallmentInterspace { get; set; }
        public Nullable<bool> LoanPayOff { get; set; }
        public string LoanDescription { get; set; }
        public Nullable<int> Loan_Account_Id { get; set; }
    }
}
