//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonnel
    {
        public int Id { get; set; }
        public Nullable<int> Personnel_Info_Id { get; set; }
        public string PersonnelId { get; set; }
        public string PersonnelMembership { get; set; }
        public string PersonnelMembershipDate { get; set; }
        public string PersonnelBARCode { get; set; }
        public string PersonnelQRCode { get; set; }
        public string PersonnelSignature { get; set; }
    }
}
