//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerAccType
    {
        public int Id { get; set; }
        public Nullable<int> PerAccType_Personnel_Id { get; set; }
        public Nullable<int> PerAccType_AccountType_Id { get; set; }
        public string PerAccTypeAccountNumber { get; set; }
    }
}
