//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWage
    {
        public int Id { get; set; }
        public Nullable<int> Wage_Loan_Id { get; set; }
        public Nullable<byte> Wage_WageType_Id { get; set; }
        public Nullable<byte> Wage_WageCalculationType_Id { get; set; }
        public string WagePercent { get; set; }
        public Nullable<long> WageAmount { get; set; }
        public string WageDescription { get; set; }
    }
}
