//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewChMoPayInfo
    {
        public int Id { get; set; }
        public Nullable<int> Account_Personnel_Id { get; set; }
        public Nullable<byte> Account_PaymentType_Id { get; set; }
        public Nullable<byte> Account_TransactionType_Id { get; set; }
        public Nullable<long> AccountAmount { get; set; }
        public string AccountReceiptNumber { get; set; }
        public Nullable<long> AccountCurrentBalance { get; set; }
        public string AccountPaymentDate { get; set; }
        public string AccountDescription { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> ChMoPay_ChargeMonthly_Id { get; set; }
        public Nullable<long> ChMoPayDueAmount { get; set; }
        public string ChMoPayDueDate { get; set; }
        public Nullable<short> ChMoPayDelayMonth { get; set; }
        public string TransactionType { get; set; }
        public string PaymentType { get; set; }
    }
}
