//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewInsLoan
    {
        public Nullable<int> Loan_Personnel_Id { get; set; }
        public Nullable<bool> LoanPayOff { get; set; }
        public Nullable<long> InstallmentDueAmount { get; set; }
        public Nullable<long> InstallmentAmount { get; set; }
        public Nullable<int> Guarantor_Info_Id { get; set; }
        public Nullable<byte> Guarantor_BlockType_Id { get; set; }
        public Nullable<bool> GuarantorBlock { get; set; }
        public Nullable<long> GuarantorBlockAmount { get; set; }
        public int Id { get; set; }
    }
}
