//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPersonnelInfo
    {
        public string PersonnelId { get; set; }
        public string PersonnelMembership { get; set; }
        public string PersonnelMembershipDate { get; set; }
        public string PersonnelBARCode { get; set; }
        public string PersonnelQRCode { get; set; }
        public string InfoNationalCode { get; set; }
        public string InfoFirstName { get; set; }
        public string InfoLastName { get; set; }
        public string InfoFatherName { get; set; }
        public string InfoCode { get; set; }
        public string InfoGender { get; set; }
        public string InfoBirthDay { get; set; }
        public string InfoBirthPlace { get; set; }
        public string InfoMarried { get; set; }
        public string InfoTell { get; set; }
        public string InfoMobile { get; set; }
        public string InfoEmail { get; set; }
        public string InfoPostalCode { get; set; }
        public string InfoAddress { get; set; }
        public string InfoJobName { get; set; }
        public string InfoJobPlaceName { get; set; }
        public string InfoJobTell { get; set; }
        public string InfoJobFax { get; set; }
        public string InfoJobAddress { get; set; }
        public string InfoImage { get; set; }
        public string InfoDescription { get; set; }
        public string PersonnelSignature { get; set; }
        public int Id { get; set; }
        public Nullable<int> Personnel_Info_Id { get; set; }
    }
}
